/*
 * conf_sd.h
 *
 * Created: 26.07.2023 19:04:48
 *  Author: qzmn
 */ 


#ifndef CONF_SD_H_
#define CONF_SD_H_

#define SD_MISO_PIN			PIN_PA08
#define SD_CS_PIN			PIN_PA09
#define SD_MOSI_PIN			PIN_PA10
#define SD_SCLK_PIN			PIN_PA11
// #define SD_POWER_PIN		PIN_PB09

#define SD_SERCOM			SERCOM0

// MUX_SETTING_E: DIPO = 0, DOPO = 1 -> PAD0 = MISO, PAD1 = CS, PAD2 = MOSI, PAD3 = SCK
#define SD_SPI_SERCOM_MUX_SETTING			SPI_SIGNAL_MUX_SETTING_E
#define SD_SPI_SERCOM_PINMUX_PAD0_MISO		PINMUX_PA08C_SERCOM0_PAD0
#define SD_SPI_SERCOM_PINMUX_PAD1_CS		PINMUX_UNUSED
#define SD_SPI_SERCOM_PINMUX_PAD2_MOSI		PINMUX_PA10C_SERCOM0_PAD2
#define SD_SPI_SERCOM_PINMUX_PAD3_SCK		PINMUX_PA11C_SERCOM0_PAD3
#define SD_SPI_TRANSFER_MODE				SPI_TRANSFER_MODE_0
#define SD_SPI_BAUDRATE						400000UL
#define SD_SPI_BAUDRATE_FAST				8000000UL
#define SD_SPI_GENERATOR_SOURCE				GCLK_GENERATOR_0

#endif /* CONF_SD_H_ */